export const events = [
  {
    "id": "event-1",
    "title": "Campus Careers Fair",
    "description": "Meet employers and explore internship opportunities.",
    "tag": "Careers",
    "organizerId": "careers",
    "dueDate": "2026-10-14",
    "duration": 120,
    "venue": "Student Centre",
    "price": 0,
    "registrationUrl": "",
    "image": "assets/event-1.svg",
    "popularity": 84,
    "recentInterest": 18,
    "createdAt": "2026-10-01T12:00:00.000Z",
    "updatedAt": "2026-10-01T12:00:00.000Z"
  },
  {
    "id": "event-2",
    "title": "CV Clinic",
    "description": "Build a stronger CV with practical feedback from peers.",
    "tag": "Workshop",
    "organizerId": "careers",
    "dueDate": "2026-10-12",
    "duration": 60,
    "venue": "Learning Hub",
    "price": 0,
    "registrationUrl": "",
    "image": "assets/event-2.svg",
    "popularity": 120,
    "recentInterest": 9,
    "createdAt": "2026-10-02T12:00:00.000Z",
    "updatedAt": "2026-10-02T12:00:00.000Z"
  },
  {
    "id": "event-3",
    "title": "Student Community Mixer",
    "description": "Meet fellow students and make new campus connections.",
    "tag": "Social",
    "organizerId": "council",
    "dueDate": "2026-10-16",
    "duration": 90,
    "venue": "Campus Courtyard",
    "price": 0,
    "registrationUrl": "",
    "image": "assets/event-3.svg",
    "popularity": 35,
    "recentInterest": 24,
    "createdAt": "2026-10-03T12:00:00.000Z",
    "updatedAt": "2026-10-03T12:00:00.000Z"
  },
  {
    "id": "event-4",
    "title": "Campus Football Session",
    "description": "Take a study break and join a friendly afternoon game.",
    "tag": "Sports",
    "organizerId": "sports",
    "dueDate": "2026-10-10",
    "duration": 75,
    "venue": "Campus Field",
    "price": 0,
    "registrationUrl": "",
    "image": "assets/event-4.svg",
    "popularity": 62,
    "recentInterest": 6,
    "createdAt": "2026-10-04T12:00:00.000Z",
    "updatedAt": "2026-10-04T12:00:00.000Z"
  },
  {
    "id": "event-5",
    "title": "Build Your First Website",
    "description": "Turn a simple idea into a website with a hands-on coding session.",
    "tag": "Workshop",
    "organizerId": "council",
    "dueDate": "2026-10-17",
    "duration": 120,
    "venue": "Computer Lab",
    "price": 0,
    "registrationUrl": "",
    "image": "assets/event-5.svg",
    "popularity": 97,
    "recentInterest": 31,
    "createdAt": "2026-10-05T12:00:00.000Z",
    "updatedAt": "2026-10-05T12:00:00.000Z"
  },
  {
    "id": "event-6",
    "title": "Creative Open Mic",
    "description": "Share a poem, a song, or a story with your campus community.",
    "tag": "Arts",
    "organizerId": "council",
    "dueDate": "2026-10-23",
    "duration": 90,
    "venue": "Student Lounge",
    "price": 5,
    "registrationUrl": "",
    "image": "assets/event-6.svg",
    "popularity": 76,
    "recentInterest": 15,
    "createdAt": "2026-10-06T12:00:00.000Z",
    "updatedAt": "2026-10-06T12:00:00.000Z"
  },
  {
    "id": "event-7",
    "title": "Morning Mindfulness",
    "description": "Start the day with a gentle guided mindfulness practice.",
    "tag": "Wellbeing",
    "organizerId": "sports",
    "dueDate": "2026-10-11",
    "duration": 30,
    "venue": "Garden Terrace",
    "price": 0,
    "registrationUrl": "",
    "image": "assets/event-7.svg",
    "popularity": 42,
    "recentInterest": 12,
    "createdAt": "2026-10-07T12:00:00.000Z",
    "updatedAt": "2026-10-07T12:00:00.000Z"
  },
  {
    "id": "event-8",
    "title": "Founders Masterclass",
    "description": "Explore how founders turn student projects into sustainable ventures.",
    "tag": "Masterclass",
    "organizerId": "careers",
    "dueDate": "2026-10-21",
    "duration": 150,
    "venue": "Auditorium",
    "price": 10,
    "registrationUrl": "",
    "image": "assets/event-8.svg",
    "popularity": 140,
    "recentInterest": 27,
    "createdAt": "2026-10-08T12:00:00.000Z",
    "updatedAt": "2026-10-08T12:00:00.000Z"
  },
  {
    "id": "event-9",
    "title": "Weekend Run Club",
    "description": "An easy-paced campus run followed by coffee and conversation.",
    "tag": "Sports",
    "organizerId": "sports",
    "dueDate": "2026-10-24",
    "duration": 45,
    "venue": "Campus Gate",
    "price": 0,
    "registrationUrl": "",
    "image": "assets/event-9.svg",
    "popularity": 105,
    "recentInterest": 36,
    "createdAt": "2026-10-09T12:00:00.000Z",
    "updatedAt": "2026-10-09T12:00:00.000Z"
  }
];
export const organizers = [
  {
    "id": "careers",
    "name": "Careers Office",
    "logo": "assets/careers-logo.svg"
  },
  {
    "id": "council",
    "name": "Student Council",
    "logo": "assets/council-logo.svg"
  },
  {
    "id": "sports",
    "name": "Campus Sports",
    "logo": "assets/sports-logo.svg"
  }
];
